---
  # Play2 - Application Server related tasks
  - name: Play app - Create test directories
    hosts: appservers
    become: yes
    become_user: root
    tasks:
      - name: create a directory for apache tomcat
        file:
          path: /tmp/tmp-oracle
          owner: root
          group: root
          state: present
          mode: 0755